SELECT * FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT * FROM EMPLOYEES WHERE B_DATE BETWEEN '1970-01-01' AND '1979-12-31'; 

SELECT * FROM EMPLOYEES WHERE B_DATE LIKE '197%';

SELECT * FROM EMPLOYEES
WHERE DEP_ID = 5 AND SALARY BETWEEN 60000 AND 70000;

SELECT * FROM EMPLOYEES ORDER BY DEP_ID;

SELECT * FROM EMPLOYEES ORDER BY DEP_ID DESC, L_NAME DESC;

